### PR TITLE
Upgrade JaneStreet async and core to v.0.16

### PR DESCRIPTION
**Pull request by tmcgilchrist**
Minor fixes to deprecated functions and function interfaces.

### CODE REVIEW

**Comment by hannesm** [comment]
Thanks for your effort. Asking @torinnd for a review since he has contributed the original async port of tls, and knows much more about async than me.

**Comment by torinnd** [comment]
Sequential is indeed the right choice, and the other changes are also pretty reasonable. I'm happy with this change. Ocaml-CI, on the other hand, seems to have some experimental checks complaining, but I can't speak to that!

**Comment by tmcgilchrist** [comment]
The linting check is suggesting these changes to opam files (it is ignorable) based on looking at the dune and opam files in the project:
```
tls-eio.opam: changes needed:
  "ptime" {>= "1.1.0"}                     [from eio]
  "logs" {with-test & >= "0.7.0"}          [from eio/tests]
tls-lwt.opam: changes needed:
  "ptime" {>= "1.1.0"}                     [from lwt]
```
Note: version numbers are just suggestions based on the currently installed version.
The other errors are for macOS ARM64, there might be a problem there with the EIO mdx tests, unreleased to this change. I don't have access to a suitable machine to check.

**Comment by tmcgilchrist** [comment]
@hannesm an opam release of this would be helpful once you're happy with the changes.

**Comment by hannesm** [comment]
> @hannesm an opam release of this would be helpful once you're happy with the changes.

would you mind to clarify two points:
- why would a release be helpful? I thought existing tls releases work with newer JS packages?
- why is there now a bound on 0.16.1? your commit says "include minor fix from ... to build on 5.1" -- but this just increases the lower bound of core to 0.16.1 (I find this highly suspicious, as I understand there is an issue to compile core 0.16.0 on ocaml 5.1, but this isn't anything that should affect tls-async... make the bounds for ocaml in core 0.16.0 / 0.16.1 tight enough, and you won't get that core 0.16.0 on ocaml 5.1)

**Comment by hannesm** [comment]
oops, about the first point, I can see that any released tls-async actually doesn't work with the 0.16 series. still, please explain the bounds to core 0.16.1.

**Comment by hannesm** [comment]
manually cherry-picked and pushed the first commit, thanks.

**Comment by tmcgilchrist** [comment]
> please explain the bounds to core 0.16.1.

Core v0.16.0 has a compilation error on OCaml 5.1 alpha2, which is fixed in v0.16.1 https://github.com/ocaml/opam-repository/pull/24025.  I was trying to include two fixes in the one PR :-)

The first commit https://github.com/mirleft/ocaml-tls/pull/476/commits/f11ea05f5697be2d215172ed0d02bce77cf42c1e will solve things for the current released OCaml versions, thank you for the quick release. That unblocks my work on http2/grpc.  The second commit is necessary to support 5.1 in the future. I will create another PR to cover 5.1 support.
